### ISSUE TITLE
安装appdirs报错

### ISSUE THREAD

**Issue by Dbraum** [debugtalk/Stormer#3]
你好，我的操作系统是mac，python版本是2.7.13，根据你的文档，我执行
```
pip install -r requirements.txt --upgrade
```
出错，报的是appdirs的问题，我修改appdirs==1.4.0 为 appdirs==1.4.3 ，则安装成功，但是执行
```
python main.py -h
```
出错，错误信息如下

```
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from stormer.logger import logger
  File "/Users/mac_cn/work/seckill/Stormer/stormer/logger.py", line 2, in <module>
    from locust.log import setup_logging
  File "/Users/mac_cn/work/seckill/Stormer/storm/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/Users/mac_cn/work/seckill/Stormer/stormer/locust.py", line 6, in <module>
    from locust import runners
ImportError: cannot import name runners
```

**Comment by debugtalk** [comment]
感谢反馈！

当前项目我开发时是采用的Python3，还没有针对Python2.7版本做适配。

另外，`from locust import runners`是依赖于已安装的`locust`，你需要确保`locust`已安装正确。

```bash
(locust) ➜ python
Python 3.6.0 (default, Feb  6 2017, 18:53:09) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from locust import runners
>>> 
```

**Comment by Dbraum** [comment]
感谢，我把环境切换到了3.6.0，重新安装就可以使用了
我想请问下，你的locust是0.8a2，我自己通过以下方式安装
```
pip install locustio==0.8a2
```
但是web界面还是没办法显示chart选项，请问您是怎么做到的。

**Comment by debugtalk** [comment]
通常pip安装的库都比源码滞后一些，可以直接通过github源码安装最新的。

```bash
$ pip install git+https://github.com/locustio/locust.git@master#egg=locustio
```

在`requirements.txt`里面已经是locust的源码地址了，你采用`pip install -r requirements.txt --upgrade`应该就是安装最新的才对。
